name: sfc_mobile
description: "Aplikasi Kasir - Comprehensive POS System"
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.4.9
  
  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Storage
  shared_preferences: ^2.2.3
  
  # PDF & Printing
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Bluetooth Printing
  flutter_blue_plus: ^1.35.5
  permission_handler: ^11.3.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.68.0
  
  # Export functionality
  csv: ^6.0.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  
  # Enhanced UI/UX
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  
  # Advanced Components
  flutter_slidable: ^3.1.0
  pull_to_refresh: ^2.0.0
  flutter_speed_dial: ^7.0.0
  badges: ^3.1.2
  
  # Enhanced Forms & Validation
  form_validator: ^2.1.1
  flutter_form_builder: ^9.2.1
  
  # Image & Media
  image_picker: ^1.0.7
  
  # Notifications
  flutter_local_notifications: ^17.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
